// Generated by nuxi
/// <reference types="@nuxt/image" />
/// <reference types="@formkit/nuxt" />
/// <reference types="nuxt-lodash" />
/// <reference types="nuxt-simple-sitemap" />
/// <reference types="nuxt-icon" />
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="@vueuse/nuxt" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="vite/client" />
/// <reference types="@formkit/vue" />
/// <reference path="module/nuxt-site-config.d.ts" />
/// <reference path="module/nuxt-simple-sitemap.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="nuxt-config-schema" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
